### ISSUE TITLE
Brew fails to install the step (Non-checksummed download of formula file from an arbitrary URL)

### ISSUE THREAD

**Issue by tobiasjordan** [BirmacherAkos/bitrise-step-xctest-html-report#17]
It seems that due to recent changes in brew, the command to install the step:
`brew "install" "https://raw.githubusercontent.com/TitouanVanBelle/XCTestHTMLReport/develop/xchtmlreport.rb"`

doesn't work anymore because brew fails with: 
`Error: Calling Non-checksummed download of xchtmlreport formula file from an arbitrary URL is disabled! Use 'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead.`

**Comment by BirmacherAkos** [comment]
Thanks @tobiasjordan, it seems they [reported the same issue](https://github.com/TitouanVanBelle/XCTestHTMLReport/issues/182) to the XCTestHTMLReport tool as well.
I'm thinking of using the [cURL command](https://github.com/TitouanVanBelle/XCTestHTMLReport#alternate) for the install. It may fix the issue.

**Comment by BirmacherAkos** [comment]
Hey @tobiasjordan there is a new version of the step [1.0.0](https://github.com/BirmacherAkos/bitrise-step-xctest-html-report/releases/tag/1.0.0), which installs the tool with the cURL command.

The release is still waiting to be approved https://github.com/bitrise-io/bitrise-steplib/pull/2669, until then you can lock the step on the master branch by changing in the bitrise.yml:
```
- xctest-html-report@0.1.3:
```

to 

```
- git::https://github.com/BirmacherAkos/bitrise-step-xctest-html-report.git@master:
```
