### ISSUE TITLE
[Question] Is this step support multiple report.xcresult

### ISSUE THREAD

**Issue by moatazeldebsy** [BirmacherAkos/bitrise-step-xctest-html-report#20]
Hi there, 
Is this step support multiple `report.xcresult` because we have multiple files and with the normal `XCTestHTMLReport` we can generate HTML file from multiple `xcresult`

Thank You!

**Comment by BirmacherAkos** [comment]
Hey @moatazeldebsy 👋,
the step does not support multiple `.xcresult` yet, but the **XCTestHTMLReport** tool [does](https://github.com/TitouanVanBelle/XCTestHTMLReport#multiple-result-bundle-path), so I'll try to add this option to the step as well.

**Comment by BirmacherAkos** [comment]
Sorry I haven't drunk my coffee yet 🤦‍♂️ 
The step **does support** multiple `.xcresult`. You can add multiple results to the **Xcode test result (.xctestresult) paths** input of the step separated by a new line.

<img width="1019" alt="Screenshot 2020-10-25 at 10 18 48" src="https://user-images.githubusercontent.com/37296013/97103247-86b29000-16ab-11eb-9fc4-1c4464f9030d.png">

**Comment by BirmacherAkos** [comment]
I'm closing this issue as the step already supports the multiple results.
