### ISSUE TITLE
Issue in displaying the report details

### ISSUE THREAD

**Issue by moatazeldebsy** [BirmacherAkos/bitrise-step-xctest-html-report#21]
Hi there, 
after using the step, the report is generated but there is no data in it
<img width="1653" alt="Screenshot 2020-10-23 at 23 10 07" src="https://user-images.githubusercontent.com/45570191/97054420-0bef5500-1585-11eb-9f12-74592f325fd3.png">

**Comment by BirmacherAkos** [comment]
Hey @moatazeldebsy, thanks for the issue report.
TBH I have no idea that this is a Bitrise ( settings for the webpage ) related issue or an issue in the used [XCTestHTMLReport](https://github.com/TitouanVanBelle/XCTestHTMLReport) tool 🤔.

I've found a similar issue ( from 2018 ) on the tool's Github page: https://github.com/TitouanVanBelle/XCTestHTMLReport/issues/90

I sent a question to Bitrise support related to this issue, maybe they know something about it.

---

For now, you can  download & open the generated HTML in a new tab as a workaround:
![tab](https://user-images.githubusercontent.com/37296013/97102317-aabea300-16a4-11eb-96e3-8d7596ffbfdb.gif)

**Comment by BirmacherAkos** [comment]
Hey @moatazeldebsy, I've got a response to the question from Bitrise.

" For security reasons, we disabled the ability to run scripts in embed HTML-s, so probably that’s why it’s not showing the results on the page."

---

Seems we have to go with the download & open in a new tab workaround.
